[package]
name = "patternfly-yew"
version = "0.0.3"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Patternfly 4 components for Yew"
repository = "https://github.com/ctron/patternfly-yew"
categories = ["wasm", "web-programming", "gui"]
keywords = ["yew", "patternfly", "web", "html"]
readme = "README.md"

[dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"

serde_json = "1"

yew = "0.17"
yew-router = { version = "0.14", optional = true }
js-sys = "0.3"
web-sys = "0.3"

log = "0.4"

[features]
default = ["router"]
router = ["yew-router"]
