[package]
name = "patternfly-yew"
version = "0.0.1"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"

yew = "0.17"
yew-router = { version = "0.14", optional = true }

log = "0.4"

[features]
default = ["router"]
router = ["yew-router"]