[package]
name = "patternfly-yew"
version = "0.0.1"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Patternfly 4 components for Yew"
repository = "https://github.com/ctron/patternfly-yew"
categories = ["wasm", "web-programming", "gui"]
keywords = ["yew", "patternfly", "web", "html"]
readme = "README.md"

[dependencies]
wasm-bindgen = "0.2"

yew = "0.17"
yew-router = { version = "0.14", optional = true }

log = "0.4"

[features]
default = ["router"]
router = ["yew-router"]