[package]
name = "patternfly-yew"
version = "0.2.3"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2021"
license = "Apache-2.0"
description = "PatternFly 4 components for Yew"
repository = "https://github.com/ctron/patternfly-yew"
categories = ["wasm", "web-programming", "gui"]
keywords = ["yew", "patternfly", "web", "html"]
readme = "README.md"

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

serde = "1"
serde_json = "1"

yew = "0.19"
yew-router = { version = "0.16", optional = true, package = "yew-router-nested" }
yew-agent = "0.1"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "HtmlCollection",
    "NodeList",
    "DomRect",
    "DomTokenList",
    "HtmlSelectElement",
    "HtmlOptionElement",
    "HtmlOptionsCollection",
    "Touch",
    "TouchEvent",
    "TouchList",
] }

chrono = { version = "0.4", features = ["wasmbind"] }

log = "0.4"

strum = "0.24"
strum_macros = "0.24"

uuid = { version = "1", features = ["v4", "js"] }

gloo-events = "0.1.2"
gloo-timers = "0.2.4"
gloo-utils = "0.1.5"

[features]
default = ["router"]
router = ["yew-router"]

[patch.crates-io]
#yew-router-nested= { version = "0.16", path = "../yew-router/yew-router-nested", optional = true }