name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        toolchain:
          - stable
          - "1.62"

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust ${{ matrix.toolchain }}
        run: |
          rustup toolchain install ${{ matrix.toolchain }} --component rustfmt,clippy --target wasm32-unknown-unknown
          rustup default ${{ matrix.toolchain }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      - name: Check rustfmt
        run:
          cargo fmt --all -- --check

      - name: Check
        run: |
          cargo check --release

      - name: Test
        run: |
          cargo test --release

      - run: cargo install cargo-all-features

      - name: Check all features
        run: |
          check-all-features --target wasm32-unknown-unknown
